{% set name = "redis-logs" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/redis-logs-{{ version }}.tar.gz
  sha256: 415c4989917955bef5f9ce80c9787446faf895ee8ba431bc8513257731d54d46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - redis-py

test:
  imports:
    - rlh
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Iglesys347/redis-log-handler
  summary: Python log handler to forward logs to Redis database
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beenje
